
export default {
  namespaced: true,
  state: {
    usersHeaders: [
      { value: 'Фамилия', sorted: false, textAlign: 'center' },
      { value: 'Имя', sorted: false, textAlign: 'center' },
      { value: 'Отчество', sorted: false, textAlign: 'center' },
      { value: 'Почта', sorted: false, textAlign: 'center' },
      { value: 'Роль', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
    ],
    directDeliveryHeaders:  [
      { value: 'Ид. транзакции', sorted: true, textAlign: 'left' },
      { value: 'Дата УПД', sorted: true, textAlign: 'center' },
      { value: 'Номер УПД', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'ИНН отправителя', sorted: false, textAlign: 'center' },
      { value: 'Организация отправитель', sorted: false, textAlign: 'left' },
      { value: 'Код поставщика', sorted: false, textAlign: 'center' },
      { value: 'ИНН получателя', sorted: false, textAlign: 'center' },
      { value: 'Организация получатель', sorted: false, textAlign: 'left' },
      { value: 'Код объекта', sorted: false, textAlign: 'center' },
      { value: 'Наименование объекта', sorted: false, textAlign: 'left' },
      { value: 'Создан', sorted: true, textAlign: 'center'},
      { value: 'Обновлен', sorted: true, textAlign: 'center'},
    ],
    universalCorrectionHeaders:  [
      { value: 'Дата УКД', sorted: false, textAlign: 'center' },
      { value: 'Номер УКД', sorted: false, textAlign: 'center' },
      { value: 'Номер предыдущего\nдокумента', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Создан', sorted: false, textAlign: 'center' },
      { value: 'Обновлен', sorted: false, textAlign: 'center' },
    ],
    universalCorrectionHeadersExternalShipment:  [
      { value: 'Дата УКД', sorted: false, textAlign: 'center' },
      { value: 'Номер УКД', sorted: false, textAlign: 'center' },
      { value: 'Номер предыдущего\nдокумента', sorted: false, textAlign: 'center' },
      { value: 'Бизнес процесс', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Создан', sorted: false, textAlign: 'center' },
      { value: 'Обновлен', sorted: false, textAlign: 'center' },
    ],
    groupOptionHeaders:  [
      { value: 'Ид. транзакции', sorted: true, textAlign: 'left' },
      { value: 'Дата отгрузки', sorted: true, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Тип перемещния', sorted: false, textAlign: 'center' },
      { value: 'ИНН отправителя', sorted: false, textAlign: 'center' },
      { value: 'Организация отправителя', sorted: false, textAlign: 'left' },
      { value: 'Код объекта отправителя', sorted: false, textAlign: 'center' },
      { value: 'Наименование объекта отправителя', sorted: false, textAlign: 'left' },
      { value: 'ИНН получателя', sorted: false, textAlign: 'center' },
      { value: 'Организация получатель', sorted: false, textAlign: 'left' },
      { value: 'Код объекта получателя', sorted: false, textAlign: 'center' },
      { value: 'Наименование объекта получателя', sorted: false, textAlign: 'left' },
      { value: 'Создан', sorted: true, textAlign: 'center' },
      { value: 'Обновлен', sorted: true, textAlign: 'center' },
    ],
    tableUpdHeaders: [
      { value: '№ строки', sorted: false, textAlign: 'center' },
      { value: 'Код товара', sorted: false, textAlign: 'center' },
      { value: 'Наименование товара', sorted: false, textAlign: 'left' },
      { value: 'Количество', sorted: false, textAlign: 'center' },
      { value: 'Ед. измерения', sorted: false, textAlign: 'center' },
    ],
    kizHeaders: [
      { value: 'Дата и время операции', sorted: false, textAlign: 'center' },
      { value: 'Бизнес-процесс', sorted: false, textAlign: 'center' },
      { value: 'Наименование операции', sorted: false, textAlign: 'left' },
      { value: 'Статус операции', sorted: false, textAlign: 'center' },
      { value: 'Комментарий', sorted: false, textAlign: 'left' },
      { value: 'Документ', sorted: false, textAlign: 'left' },
      { value: 'Владелец марки', sorted: false, textAlign: 'center' },
      { value: 'Местоположение', sorted: false, textAlign: 'center' },
    ],
    kizUkdHeaders: [
      { value: '№\nстроки', sorted: false, textAlign: 'center' },
      { value: 'Наименование\nпродукции', sorted: false, textAlign: 'left' },
      { value: 'КИЗ', sorted: false },
    ],
    historyHeaders: [
      { value: 'Дата и время операции', sorted: false, textAlign: 'center' },
      { value: 'Наименование операции', sorted: false, textAlign: 'left' },
      { value: 'Статус документа', sorted: false, textAlign: 'center' },
      { value: 'Комментарий', sorted: false, textAlign: 'left' },
    ],
    marksHeaders: [
      { value: 'КИЗ', sorted: false, textAlign: 'center' },
      { value: 'Уровень упаковки', sorted: false, textAlign: 'center' },
      { value: 'GTIN', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },

    ],
    suzHeaders: [
      { value: 'Ид. транзакции', sorted: true, textAlign: 'left' },
      { value: 'Ид. производственного заказа', sorted: true, textAlign: 'left' },
      { value: 'Товарная группа', sorted: false, textAlign: 'left' },
      { value: 'Способ выпуска КМ', sorted: false, textAlign: 'center' },
      { value: 'Организация', sorted: false, textAlign: 'left' },
      { value: 'Объект', sorted: false, textAlign: 'center' },
      { value: 'Кол-во товаров', sorted: false, textAlign: 'center' },
      { value: 'Количество КМ', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Создан', sorted: true, textAlign: 'center' },
      { value: 'Обновлен', sorted: true, textAlign: 'center' },
    ],
    tableSuzHeaders: [
      { value: 'Номер строки', sorted: false, textAlign: 'center' },
      { value: 'Код PLU', sorted: false, textAlign: 'center' },
      { value: 'GTIN', sorted: false, textAlign: 'center' },
      { value: 'Наименование товара', sorted: false, textAlign: 'left' },
      { value: 'Кол-во КМ', sorted: false, textAlign: 'center' },
      { value: 'Получено КМ', sorted: false, textAlign: 'center' },
      { value: 'Кол-во блоков', sorted: false, textAlign: 'center' },
      { value: 'Кол-во коробов', sorted: false, textAlign: 'center' },
      { value: 'Кол-во паллет', sorted: false, textAlign: 'center' },
      { value: 'Статус агрегации', sorted: false, textAlign: 'center' },
    ],
    commissioningHeaders: [
      { value: 'Ид. транзакции', sorted: true, textAlign: 'left' },
      { value: 'Товарная группа', sorted: false, textAlign: 'left' },
      { value: 'Тип документа', sorted: false, textAlign: 'center' },
      { value: 'Ид. заказа', sorted: false, textAlign: 'left' },
      { value: 'Организация', sorted: false, textAlign: 'left' },
      { value: 'Объект', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Создан', sorted: true, textAlign: 'center' },
      { value: 'Обновлен', sorted: true, textAlign: 'center' },
    ],
    tableCommissioningHeaders: [
      { value: 'КИЗ', sorted: false, textAlign: 'center' },
      { value: 'Код PLU', sorted: false, textAlign: 'center' },
      { value: 'GTIN', sorted: false, textAlign: 'center' },
      { value: 'Наименование', sorted: false, textAlign: 'left' },
      { value: 'Код ТНВЭД', sorted: false, textAlign: 'center' },
      { value: 'Кол-во единиц\nвнутри', sorted: false, textAlign: 'center' },
      { value: 'Принадлежит\nзаказу?', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
    ],
    leavingHeaders: [
      { value: 'Ид. транзакции', sorted: true, textAlign: 'left' },
      { value: 'Товарная группа', sorted: false, textAlign: 'left' },
      { value: 'Тип документа', sorted: false, textAlign: 'center' },
      { value: 'Номер документа', sorted: true, textAlign: 'left' },
      { value: 'Дата документа', sorted: false, textAlign: 'center' },
      { value: 'Организация', sorted: false, textAlign: 'left' },
      { value: 'Объект', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Создан', sorted: true, textAlign: 'center' },
      { value: 'Обновлен', sorted: true, textAlign: 'center' },
    ],
    tableIncomingHeaders: [
      { value: 'КИЗ', sorted: false, textAlign: 'center' },
      { value: 'Код PLU', sorted: false, textAlign: 'center' },
      { value: 'Наименование', sorted: false, textAlign: 'left' },
      { value: 'GTIN', sorted: false, textAlign: 'center' },
      { value: 'Кол-во единиц\nвнутри', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
    ],
    incomingHeaders: [
      { value: 'Ид.транзакции', sorted: true, textAlign: 'left' },
      { value: 'Ид. заказа', sorted: false, textAlign: 'left' },
      { value: 'Организация', sorted: true, textAlign: 'left' },
      { value: 'Объект', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Создан', sorted: true, textAlign: 'center' },
      { value: 'Обновлен', sorted: true, textAlign: 'center' },
    ],
    tableLeavingHeaders: [
      { value: 'КИЗ', sorted: false, textAlign: 'center' },
      { value: 'Код PLU', sorted: false, textAlign: 'center' },
      { value: 'GTIN', sorted: false, textAlign: 'center' },
      { value: 'Наименование', sorted: false, textAlign: 'left' },
      { value: 'Кол-во единиц\nвнутри', sorted: false, textAlign: 'center' },
      { value: 'Проверка КИ', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
    ],
    subordersHeaders: [
      { value: 'Номер строки', sorted: false, textAlign: 'center' },
      { value: 'GTIN', sorted: true, textAlign: 'center' },
      { value: 'Ид. документа в ГИС', sorted: true, textAlign: 'center' },
      { value: 'Кол-во КМ в подзаказе', sorted: false, textAlign: 'center' },
      { value: 'Получено КМ', sorted: false, textAlign: 'center' },
      { value: 'Статус обработки в ГИС', sorted: false, textAlign: 'center' },
      { value: 'Текст ошибки', sorted: true, textAlign: 'left' },
    ],
    aggregationHeaders: [
      { value: 'Ид. транзакции', sorted: true, textAlign: 'left' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Создан', sorted: true, textAlign: 'center' },
      { value: 'Обновлен', sorted: true, textAlign: 'center' },
    ],
    aggregationHeadersMain: [
      { value: 'Ид. транзакции', sorted: true, textAlign: 'left' },
      { value: 'Товарная группа', sorted: false, textAlign: 'left' },
      { value: 'Организация', sorted: false, textAlign: 'left' },
      { value: 'Объект', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'left' },
      { value: 'Создан', sorted: true, textAlign: 'center' },
      { value: 'Обновлен', sorted: true, textAlign: 'center' },
    ],
    tableAggregation: [
      { value: 'КИ', sorted: false, textAlign: 'center' },
      { value: 'Код товара', sorted: false, textAlign: 'center' },
      { value: 'Наименование товара', sorted: false, textAlign: 'center' },
      { value: 'Уровень упаковки в ГИС', sorted: false, textAlign: 'center' },
      { value: 'Тип упаковки ', sorted: false, textAlign: 'center' },
      { value: 'Кол-во единиц внутри', sorted: false, textAlign: 'center' },
      { value: 'Способ генерации кода', sorted: false, textAlign: 'center' },
    ],
    tableSubAggregation: [
      { value: 'КИ', sorted: false, textAlign: 'center' },
      { value: 'Уровень упаковки в ГИС', sorted: false, textAlign: 'center' },
      { value: 'Тип упаковки ', sorted: false, textAlign: 'center' },
      { value: 'Кол-во единиц внутри', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
    ],
    tableAggregationHeaders: [
      { value: 'КИЗ', sorted: false, textAlign: 'center' },
      { value: 'Кол-во единиц\nвнутри', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
    ],
    externalShipmentHeaders: [
      { value: 'Ид. транзакции', sorted: true, textAlign: 'left' },
      { value: 'Дата отгрузки', sorted: true, textAlign: 'center' },
      { value: 'Организация отправителя', sorted: false, textAlign: 'left' },
      { value: 'Объект отправителя', sorted: false, textAlign: 'center' },
      { value: 'Организация получателя', sorted: false, textAlign: 'left' },
      { value: 'Объект получателя', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'left' },
      { value: 'Создан', sorted: true, textAlign: 'center'},
      { value: 'Обновлен', sorted: true, textAlign: 'center'},
    ],
    tableExternalShipmentHeaders: [
      { value: '№ строки', sorted: false, textAlign: 'center' },
      { value: 'Код товара', sorted: false, textAlign: 'center' },
      { value: 'Наименование товара', sorted: false, textAlign: 'left' },
      { value: 'Количество', sorted: false, textAlign: 'center' },
      { value: 'Ед. измерения', sorted: false, textAlign: 'center' },
    ],
    externalShipmentReturnHeaders: [
      { value: 'Ид.транзакции', sorted: false, textAlign: 'center' },
      { value: 'Дата возврата', sorted: true, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Создан', sorted: true, textAlign: 'center'},
      { value: 'Обновлен', sorted: true, textAlign: 'center'},
    ],
    tableExternalReturnHeaders: [
      { value: '№ строки', sorted: false, textAlign: 'center' },
      { value: 'Код товара', sorted: false, textAlign: 'center' },
      { value: 'Наименование товара', sorted: false, textAlign: 'left' },
      { value: 'Количество', sorted: false, textAlign: 'center' },
      { value: 'Ед. измерения', sorted: false, textAlign: 'center' },
    ],
    reconciliationHeader: [
      { value: 'Ид.транзакции', sorted: true, textAlign: 'left' },
      { value: 'Тип сверки', sorted: true, textAlign: 'center' },
      { value: 'Дата документа', sorted: true, textAlign: 'center' },
      { value: 'Организация', sorted: false, textAlign: 'left' },
      { value: 'Объект', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Создан', sorted: true, textAlign: 'center' },
    ],
    reconciliationItems: [
      { value: 'GTIN', sorted: true, textAlign: 'center' },
      { value: 'Код товара', sorted: true, textAlign: 'center' },
      { value: 'Наименование товара', sorted: true, textAlign: 'left' },
      { value: 'Количество на объекте', sorted: true, textAlign: 'center' },
      { value: 'Количество в системе', sorted: true, textAlign: 'center' },
      { value: 'Расхождение', sorted: false, textAlign: 'center' },
    ],
    reconciliationItemsDetailsAppendMark: [
      { value: 'Результат сверки', sorted: true, textAlign: 'center' },
      { value: 'Количество', sorted: true, textAlign: 'center' },
    ],
    reconciliationItemsAppendMark: [
      { value: 'КИЗ', sorted: true, textAlign: 'center' },
      { value: 'Местоположение в системе', sorted: true, textAlign: 'center' },
      { value: 'Местоположение фактическое', sorted: true, textAlign: 'center' },
      { value: 'Статус', sorted: true, textAlign: 'center' },
    ],
    fundInformationHeader: [
      { value: 'КИ', sorted: true, textAlign: 'center' },
      { value: 'Объект \n' + '(КИ утрачен)', sorted: true, textAlign: 'center' },
      { value: 'Бизнес процесс', sorted: false, textAlign: 'left' },
      { value: 'Объект \n' + '(КИ найден)', sorted: true, textAlign: 'center' },
      { value: 'Бизнес процесс', sorted: false, textAlign: 'left' },
      { value: 'Документ списания', sorted: true, textAlign: 'left' },
      { value: 'Причина списания', sorted: false, textAlign: 'left' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Создан ', sorted: true, textAlign: 'center' },
      { value: 'Обновлен ', sorted: true, textAlign: 'center' },
    ],
    autoTestList: [
      { value: 'Ид. сценария', sorted: true, textAlign: 'left' },
      { value: 'Наименование сценария', sorted: true, textAlign: 'left' },
      { value: 'Всего команд', sorted: false, textAlign: 'center' },
      { value: 'Выполнено команд', sorted: false, textAlign: 'center' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
      { value: 'Создан ', sorted: true, textAlign: 'center' },
      { value: 'Обновлен ', sorted: true, textAlign: 'center' },
    ],
    autoTestListDetail: [
      { value: '', sorted: false, textAlign: 'center' },
      { value: '№', sorted: false, textAlign: 'center' },
      { value: 'Команда', sorted: false, textAlign: 'center' },
      { value: 'Содержание команды', sorted: false, textAlign: 'left' },
      { value: 'Статус', sorted: false, textAlign: 'center' },
    ],
    autoTestListSamples: [
      { value: '', sorted: false, textAlign: 'center' },
      { value: 'Наименование сценария', sorted: true, textAlign: 'left' },
      { value: 'Количество команд', sorted: false, textAlign: 'center' },
      { value: 'Создан', sorted: true, textAlign: 'center' },
      { value: 'Обновлен', sorted: true, textAlign: 'center' },
    ],
    autoTestCommand: [
      { value: '№', sorted: false, textAlign: 'center' },
      { value: 'Документ', sorted: false, textAlign: 'left' },
      { value: 'Исходящие сообщение', sorted: false, textAlign: 'left' },
      { value: 'Статус документа', sorted: false, textAlign: 'center' },
      { value: 'Комментарий', sorted: false, textAlign: 'left' },
    ],
    autoTestCreate: [
      { value: '№', sorted: false, textAlign: 'center' },
      { value: 'Команда', sorted: false, textAlign: 'center' },
      { value: 'Содержание команды', sorted: false, textAlign: 'left' },
      { value: '', sorted: false, textAlign: 'center' },
    ],

  },
  getters: {
    usersHeaders: (state) => state.usersHeaders,
    directDeliveryHeaders: (state) => state.directDeliveryHeaders,
    universalCorrectionHeaders: (state) => state.universalCorrectionHeaders,
    groupOptionHeaders: (state) => state.groupOptionHeaders,
    tableUpdHeaders: (state) => state.tableUpdHeaders,
    kizHeaders: (state) => state.kizHeaders,
    kizUkdHeaders: (state) => state.kizUkdHeaders,
    historyHeaders: (state) => state.historyHeaders,
    marksHeaders: (state) => state.marksHeaders,
    suzHeaders: (state) => state.suzHeaders,
    tableSuzHeaders: (state) => state.tableSuzHeaders,
    commissioningHeaders: (state) => state.commissioningHeaders,
    incomingHeaders: (state) => state.incomingHeaders,
    tableIncomingHeaders: (state) => state.tableIncomingHeaders,
    leavingHeaders: (state) => state.leavingHeaders,
    tableCommissioningHeaders: (state) => state.tableCommissioningHeaders,
    tableLeavingHeaders: (state) => state.tableLeavingHeaders,
    subordersHeaders: (state) => state.subordersHeaders,
    aggregationHeaders: (state) => state.aggregationHeaders,
    aggregationHeadersMain: (state) => state.aggregationHeadersMain,
    tableAggregation: (state) => state.tableAggregation,
    tableSubAggregation: (state) => state.tableSubAggregation,
    tableAggregationHeaders: (state) => state.tableAggregationHeaders,
    externalShipmentHeaders: (state) => state.externalShipmentHeaders,
    tableExternalShipmentHeaders: (state) => state.tableExternalShipmentHeaders,
    externalShipmentReturnHeaders: (state) => state.externalShipmentReturnHeaders,
    tableExternalReturnHeaders: (state) => state.tableExternalReturnHeaders,
    reconciliationHeader: (state) => state.reconciliationHeader,
    reconciliationItems: (state) => state.reconciliationItems,
    reconciliationItemsAppendMark: (state) => state.reconciliationItemsAppendMark,
    reconciliationItemsDetailsAppendMark: (state) => state.reconciliationItemsDetailsAppendMark,
    universalCorrectionHeadersExternalShipment: (state) => state.universalCorrectionHeadersExternalShipment,
    fundInformationHeader: (state) => state.fundInformationHeader,
    autoTestList: (state) => state.autoTestList,
    autoTestListDetail: (state) => state.autoTestListDetail,
    autoTestCommand: (state) => state.autoTestCommand,
    autoTestCreate: (state) => state.autoTestCreate,
    autoTestListSamples: (state) => state.autoTestListSamples

  }
}
